x = -pi:pi/10:pi;
y = tan(sin(x)) - sin(tan(x));

%Generate the Sine Signal.................
y1 = tan(cos(x)) - cos(tan(x));

% -----------------------
figure,
plot(x,y,'--gs',...
    'LineWidth',2,...
    'MarkerSize',10,...
    'MarkerEdgeColor','b',...
    'MarkerFaceColor',[0.5,0.5,0.5])
hold on
plot(x, y1, '--kd', ...
    'LineWidth',2,...
    'MarkerSize',10,...
    'MarkerEdgeColor','m',...
    'MarkerFaceColor',[0.1,0.5,0.1])

%legend('tan(sin)', 'tan(cos)')
% legend('\color{green}\bf tan(sin)', '\color{black}\bf tan(cos)')
legend({'tan(sin)','tan(cos)'},'Location','northwest','NumColumns',2)
